server:
  port: 8040
spring:
  application:
    name: uploadpicture-microservice    # 项目名称尽量用小写
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/    # 指定注册中心的地址
  instance:
    preferIpAddress: true

image:
  uploadpath: D:\\

multipart:
  enabled: true